### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by BullyWiiPlaza** [FIX94/wiiu-vc-inject#1]
I know this is old but it should compile regardless. I have[ `MinGW`](http://www.mingw.org/wiki/Getting_Started) installed in `C:\tools\mingw64` but when I run the `build.bat` file, I get the following error:
```
>gcc -s -O2 -static -Bstatic main.c -o bin/wiiu-vc-inject -lws2_32
main.c: In function 'main':
main.c:206:13: error: 'SD_SEND' undeclared (first use in this function)
  shutdown(s,SD_SEND); //sent all we have
             ^
main.c:206:13: note: each undeclared identifier is reported only once for each function it appears in
```

[After some research](http://www.mingw.org/wiki/HOWTO_Specify_the_Location_of_Libraries_for_use_with_MinGW), it seems like it couldn't link the Windows sockets library. However, the syntax seems to be correct. What could be the problem? The `GCC` location is the following:
```
>where gcc
C:\tools\mingw64\bin\gcc.exe
```

`libws2_32.a` can be found in `C:\tools\mingw64\x86_64-w64-mingw32\lib` so it should be loaded but is not.

**Comment by FIX94** [comment]
its a problem about a include probably missing, maybe in the main.c add in #include <winsock2.h> and see if that helps, mingw comes in tons of different versions and each one has something different about it.

**Comment by BullyWiiPlaza** [comment]
Yes, using `#include <winsock2.h>` instead of `#include <windows.h>` actually worked and it compiled. 👍
